### PR TITLE
RHIN-1606: Revert code of smart table

### PR DESCRIPTION
**Pull request by rosh-ttn**
✔︎ I've tested in all browsers (IE11, Firefox, Safari, Chrome, and iOS)

### What should this PR do?
Handle third issue under this Jira Ticket - 
Fill background in expandable area in mobile views #171

### Jira Link - 
https://rhinogram.atlassian.net/browse/RHIN-1606

### What is the acceptance criteria?
Not Applicable

[If there are UI changes, include a before and after screenshot.]

### CODE REVIEW

**Comment by rosh-ttn** [comment]
@abhicool957 There is no Jira ticket for this task.

**Comment by abhicool957** [comment]
@rosh-ttn : Please always ask for JIRA ticket before picking the task. We are following this as practice so that anytime tracking can be easy for us. And one more suggestion always start initial commit with JIRA ticket. Please let me know if you need more clarity.

**Comment by rosh-ttn** [comment]
@juanfabrega This is the same code that was merged into master, but it was missing from master after an eslint commit. Raising PR again for the code. Please review.

**Comment by juanfabrega** [comment]
> @juanfabrega This is the same code that was merged into master, but it was missing from master after an eslint commit. Raising PR again for the code. Please review.

Hey @rosh-ttn The same thing happened to me on a PR this week. I think that stuff is getting overwritten when we resolve merge conflicts. I will be working on a step-by-step guide to avoid this, but the short version is that I think we will have to merge with master both when starting as well as ending work on a feature. 

So basically, when we start work on a feature, we merge master into our feature branch with merge-strategy `theirs`, then when we complete the feature, before submitting the PR, we merge from master again but doing merge-strategy `ours`. I THINK that this should prevent these issues moving forward but I will try it and let you know what I find.

**Comment by juanfabrega** [comment]
@rosh-ttn hold off on merging this to ensure we don't erase changes again. I will merge shortly.

**Comment by juanfabrega** [comment]
Yes, this is probably the best approach. Although I already merged this
commit. Can you confirm it's got the latest changes on your end

**Pull request merged**
