### PR TITLE
RHIN-1371: Details/Hide Details' not working with sorting

### PR DESCRIPTION
**Pull request by mahimaag**
✔︎ I've tested in all browsers (IE11, Firefox, Safari, Chrome, and iOS)

### What should this PR do?
Details/Hide Details' not working properly after applying sorting on the audit log columns
https://rhinogram.atlassian.net/browse/RHIN-1371

### What is the acceptance criteria?
1. Expanded of rows should be working properly with sorting data

[If there are UI changes, include a before and after screenshot.]

### CODE REVIEW

**Comment by alexgsummer** [comment]
Is this fixing the bug or just updating the doc / example code?

**Comment by mahimaag** [comment]
@alexgsummer It's not fixing the bug and it will not impact anywhere. I added this only for reference for others so that nobody's will get this issue in future if follow this guidelines.

**Comment by alexgsummer** [comment]
Please wait for @juanfabrega's approval before merging.

**Comment by mahimaag** [comment]
Merging this but i don't need to release this as this change is not related to any component. It's just a guidlines and can be release when some one will release the latest change

**Pull request merged**
