### PR TITLE
added validation message into textareas

### PR DESCRIPTION
**Pull request by BlakeGuilloud**
**Related issue link:** (You can delete this line if the PR does not relate to an existing GitHub issue)

- [ ] I've tested in all browsers (IE11, Firefox, Safari, Chrome, and iOS)

### What should this PR do?
Allows for a propType of ValidationMessage to be used on text areas.

### What is the acceptance criteria?
1. Confirm that the Textarea component accepts a validationMessage in the same regards of an Input

[If there are UI changes, include a before and after screenshot.]
image

### CODE REVIEW

**Comment by zslabs** [comment]
Yo! I'm seeing a bit of weirdness when the `validationMessage` is used in conjunction with `explanationMessage`:

screen shot 2017-02-23 at 12 45 32 pm

Regular input:

screen shot 2017-02-23 at 12 45 40 pm

It looks like the `TextArea` component has a `.form__control-footer` class around those messages. While we do still need that for formatting of the character count, I'm thinking if we changed it to:

```
<div className="form__control-footer">
  <div>
    {showValidationMessage()}
    {showExplanationMessage()}
  </div>
  {showCharacterCount()}
</div>
```

This would let any validation/explanation messages be block-level when used in conjunction.

screen shot 2017-02-23 at 12 50 31 pm

cc @mcraiganthony This would make the `:empty` check in not work for `.form__control-footer` unless we do something like this:

```
<div className="form__control-footer">
  {(showValidationMessage() || showExplanationMessage()) ? 
    <div>
      {showValidationMessage()}
      {showExplanationMessage()}
    </div>
  : ''}
  {showCharacterCount()}
</div>
```

Lemme know what you think.

**Comment by mcraiganthony** [comment]
LGTM

**Comment by BlakeGuilloud** [comment]
image

**Comment by zslabs** [comment]
👍 Good to merge once conflicts are resolved.

**Pull request merged**
