### PR TITLE
RHIN-3180 -Legends are missing on New Inbound Contacts donut chart

### PR DESCRIPTION
**Pull request by vkvisooo**
✔︎ I've tested in all browsers (IE11, Firefox, Safari, Chrome, and iOS)

https://rhinogram.atlassian.net/browse/RHIN-3180

### What should this PR do?
Legends are missing on New Inbound Contacts donut chart

### What is the acceptance criteria?
1. List

image-20190821-075918

### CODE REVIEW

**Comment by abhicool957** [comment]
@benbruning : This is for rhinostyle  and yaeh branch name is wrong and create confusion

**Comment by benbruning** [comment]
@abhicool957 whoops, my bad.

**Comment by drtonton** [comment]
@vkvisooo I'm pretty unfamiliar with the use of `forceUpdate()`, but based on what I'm reading its generally not recommended unless there are no alternatives, and I can't find any examples in our codebase. Were any alternative solutions considered, and is a re-rendering fixing the issue here?

**Comment by vkvisooo** [comment]
> @vkvisooo I'm pretty unfamiliar with the use of `forceUpdate()`, but based on what I'm reading its generally not recommended unless there are no alternatives, and I can't find any examples in our codebase. Were any alternative solutions considered, and is a re-rendering fixing the issue here?

@drtonton Yes re-rendering fixed the issue cause, this.chartInstance is undefined when the render method is called but after mount this.chartInstance has its value, so we have to call render method again

**Pull request merged**
